drgavrikov/leetcode

src/main/kotlin/Problem1028.kt

https://leetcode.com/problems/recover-a-tree-from-preorder-traversal/

problem-1028

---

src/main/kotlin/Problem1255.kt

https://leetcode.com/problems/maximum-score-words-formed-by-letters/submissions/

problem-1255

---

src/main/kotlin/easy/Problem1672.kt
src/test/kotlin/easy/Problem1672Test.kt

problem-1672

---

src/main/kotlin/easy/Problem1480.kt
src/test/kotlin/easy/Problem1480Test.kt

problem-1480

---

src/main/kotlin/TreeNode.kt
src/main/kotlin/easy/Problem938.kt
src/test/kotlin/easy/Problem938Test.kt

problem-938

---

src/main/kotlin/easy/Problem100.kt
src/main/kotlin/hard/Problem1028.kt
src/main/kotlin/hard/Problem987.kt
src/main/kotlin/medium/Problem222.kt
src/test/kotlin/easy/Problem100Test.kt
src/test/kotlin/medium/Problem222Test.kt
src/test/kotlin/medium/Problem987Test.kt

eliminate extra class TreeNode

eliminate extra class TreeNode

---

src/main/kotlin/medium/Problem200.kt
src/test/kotlin/medium/Problem200Test.kt

problem-200

---

src/main/kotlin/medium/Problem56.kt
src/test/kotlin/medium/Problem56Test.kt

problem-56

---

src/main/kotlin/easy/Problem2089.kt
src/test/kotlin/easy/Problem2089Test.kt

problem-2089

---

src/main/kotlin/easy/Problem2367.kt
src/test/kotlin/easy/Problem2367Test.kt

problem-2367

---

src/main/kotlin/easy/Problem637.kt
src/test/kotlin/easy/Problem637Test.kt

problem-637

---

src/main/kotlin/easy/Problem748.kt
src/test/kotlin/easy/Problem748Test.kt

problem-748

---

src/main/kotlin/easy/Problem2273.kt
src/main/kotlin/easy/Problem748.kt
src/test/kotlin/easy/Problem2273Test.kt

problem-2273

---

src/main/kotlin/easy/Problem20.kt
src/test/kotlin/easy/Problem20Test.kt

problem-20

---

src/main/kotlin/medium/Problem53.kt
src/test/kotlin/medium/Problem53Test.kt

problem-53

---

src/main/kotlin/medium/Problem54.kt
src/test/kotlin/medium/Problem54Test.kt

problem-54

---

src/main/kotlin/easy/Problem859.kt
src/test/kotlin/easy/Problem859Test.kt

problem-859

---

src/main/kotlin/medium/Problem763.kt
src/test/kotlin/medium/Problem763Test.kt

problem-763

---

src/main/kotlin/medium/Problem1011.kt
src/test/kotlin/medium/Problem1011Test.kt

problem-1011

---

src/main/kotlin/medium/Problem22.kt
src/test/kotlin/medium/Problem22Test.kt

problem-22

---

src/main/kotlin/hard/Problem41.kt
src/test/kotlin/hard/Problem41Test.kt

problem-41

---

src/main/kotlin/medium/Problem49.kt
src/test/kotlin/medium/Problem49Test.kt

problem-49

---

src/main/kotlin/medium/Problem1136.kt
src/test/kotlin/medium/Problem1136Test.kt

problem-1136

---

src/main/kotlin/medium/Problem690.kt
src/test/kotlin/medium/Problem690Test.kt

problem-690

---

src/main/kotlin/easy/Problem504.kt
src/test/kotlin/easy/Problem504Test.kt

problem-504

---

src/main/kotlin/medium/Problem652.kt
src/test/kotlin/medium/Problem652Test.kt

problem-652

---

src/main/kotlin/ListNode.kt
src/main/kotlin/medium/Problem237.kt
src/test/kotlin/medium/Problem237Test.kt

problem-237

---

src/main/kotlin/easy/Problem350.kt
src/test/kotlin/easy/Problem350Test.kt

problem-350

---

src/main/kotlin/easy/Problem20.kt
src/main/kotlin/medium/Problem833.kt
src/test/kotlin/medium/Problem833Test.kt

problem-833

---

src/main/kotlin/medium/Problem173.kt
src/test/kotlin/medium/Problem173Test.kt

problem-173

---

src/main/kotlin/medium/Problem1110.kt
src/test/kotlin/medium/Problem1110Test.kt

problem-1110

---

src/main/kotlin/medium/Problem114.kt
src/test/kotlin/medium/Problem114Test.kt

problem-114

---

src/main/kotlin/medium/Problem128.kt
src/test/kotlin/medium/Problem128Test.kt

problem-128

---

src/main/kotlin/medium/Problem238.kt
src/main/kotlin/medium/Problem652.kt
src/test/kotlin/medium/Problem238Test.kt

problem-238

---

src/main/kotlin/medium/Problem155.kt
src/test/kotlin/medium/Problem155Test.kt

problem-155

---

src/main/kotlin/medium/Problem739.kt
src/test/kotlin/medium/Problem739Test.kt

problem-739

---

src/main/kotlin/medium/Problem19.kt
src/test/kotlin/medium/Problem19Test.kt

problem-19

---

src/main/kotlin/easy/Problem141.kt
src/test/kotlin/easy/Problem141Test.kt

problem-141

---

src/main/kotlin/medium/Problem77.kt

problem-77
